name: Battles test

on: push

jobs:
    mem_test_and_cppcheck:
        runs-on: ubuntu-latest
      
        steps:
            - uses: actions/checkout@v2
            - run: sudo apt install cppcheck valgrind
            - run: g++ -Wall character.cpp player.cpp main.cpp -I player.h character.h -o mosze_01
            - run: chmod a+x ./cppcheck.sh
            - run: ./cppcheck.sh
            - uses: actions/upload-artifact@v2
              with:
                name: perfomance_style-artifact
                path: ./cppcheck_performance.txt
            - run: valgrind --leak-check=yes --error-exitcode=1 ./mosze_01 units/test_unit_1.json units/test_unit_2.json
            
    build_and_test:
        runs-on: ubuntu-latest
      
        steps:
            - uses: actions/checkout@v2
            - run: g++ -Wall character.cpp player.cpp main.cpp -I player.h character.h -o mosze_01
            - run: ./run_battle_test.sh mosze_01 program_outputs.txt
            - run: diff program_outputs.txt good_outputs.txt
            
