name: Battles test

on: push

jobs:
    mem_test_and_cppcheck:
        runs-on: ubuntu-20.04
        container: image/test_image:latest
        steps:
            - uses: actions/checkout@v2
            - run: make
            - run: make cppcheck
            - uses: actions/upload-artifact@v2
              with:
                name: perfomance_style-artifact
                path: ./cppcheck_performance.txt
            - run: make check_memoryleak
            
    build_and_test:
        runs-on: ubuntu-latest
      
        steps:
            - uses: actions/checkout@v2
            - run: make
            - run: make battle
            - run: make battle_diff
            - run: make clean
            - run: make unit_test
            
            
