name: Documentation workflow

on: pull_request

jobs:
    deploy:
        name: Deploy to Github pages
        runs-on: ubuntu-20.04
        container: kurucc/test_image
        steps:
            - uses: actions/checkout@master

            - name: Generate docs
              run: make documentation

            - name: Push git subdir branch
              uses: s0/git-publish-subdir-action@v2.4.0

              env:
                REPO: self
                BRANCH: gh-pages
                FOLDER: docs/html
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}